added the value of trust
pedroomtz17/Activity03 pull request #2
Opened 2022-10-04 14:29 UTC by pedroomtz17

Isaac, are these changes ok?

2022-10-04 15:07 UTC, IsaacRayas commented on README.md
> +Trust is the basis for everything we do and the prerequisite for our success. We keep our promises. To all our employees and all stakeholders in Continental (such as customers, employees, investors,
It's okay, just to compliment, you could add Continental's vision.

2022-10-04 15:50 UTC, IsaacRayas reviewed
It's okay, just to compliment, you could add Continental's vision.

2022-10-04 20:55 UTC, IsaacRayas requested changes
It's okay, just to compliment, you could add Continental's vision.

2022-10-05 15:31 UTC, pedroomtz17 commented
Changes made 👍

2022-10-05 15:38 UTC, IsaacRayas approved these changes
Excellent, well done

2022-10-05 15:40 UTC, merged